name: "Sphinx: Render docs"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master

      - name: Copy HTML to root directory
        run: |
          rsync -av ./docs/build/html/ ./
        working-directory: ${{ github.workspace }}/..
        
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update gh-pages with latest documentation from main"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
